name: 'XYZmart'
version: '1.0.0'
config-version: 2
profile: 'XYZmart'

model-paths: ["models"]
analysis-paths: ["sql/analysis"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

vars:
  XYZmart:
    payment_methods: ['credit_card', 'debit_card', 'apple_pay', 'line_pay']
    churn_threshold_days: 90

models:
  XYZmart:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']
    intermediate:
      +materialized: ephemeral
      +tags: ['intermediate']
    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts', 'bi']

seeds:
  XYZmart:
    +schema: seeds

snapshots:
  XYZmart:
    +target_schema: snapshots
    +strategy: timestamp
